import os
import json
import asyncio
import edge_tts
import uuid
from groq import AsyncGroq
from deep_translator import GoogleTranslator
import re

# Initialize Groq
groq_client = AsyncGroq(api_key=os.getenv("GROQ_API_KEY"))

VOICE_MAP = {
    "en": "en-IN-NeerjaNeural",
    "hi": "hi-IN-SwaraNeural",
    "ta": "ta-IN-PallaviNeural",   
    "te": "te-IN-ShrutiNeural",    
    "bn": "bn-IN-TanishaaNeural",  
    "kn": "kn-IN-SapnaNeural",     
    "mr": "mr-IN-AarohiNeural",    
    "gu": "gu-IN-DhwaniNeural",    
    "ml": "ml-IN-SobhanaNeural",   
    "or": "en-IN-NeerjaNeural"     
}

# --- THE WHISPER HALLUCINATION FILTER ---
GHOST_PHRASES = [
    "thank you", "thanks for", "subscribe", "i'm going to", "i am going to",
    "am going to", "watching", "bye", "subtitles", "generated by", "going to do"
]

def is_hallucination(text: str) -> bool:
    """Detects if Whisper hallucinated based on background static."""
    t = text.lower().strip()
    # Remove punctuation for cleaner matching
    t = re.sub(r'[^\w\s]', '', t)
    
    if len(t) < 3: 
        return True
    for phrase in GHOST_PHRASES:
        # If the transcript is mostly just the hallucinated phrase, block it
        if phrase in t and len(t) < len(phrase) + 15:
            return True
    return False


# --- THE UPGRADED SYSTEM PROMPT ---
SYSTEM_PROMPT = """
You are 'Saheli', a warm, patient, and empathetic onboarding assistant for Saheli Crafts. You are on a live phone call with an Indian artisan or small business owner.

YOUR PERSONA:
- You are having a real-time voice conversation. 
- Keep your replies EXTREMELY SHORT (1 to 2 sentences maximum). 
- Speak like a friendly human, not a robot. Use natural affirmations like "Got it," "Perfect," "Great," or "Nice to meet you."

YOUR MISSION (THE STATE MACHINE):
You must collect the following 9 pieces of information in this EXACT order. 
RULE 1: NEVER ask for two things at once. 
RULE 2: Always wait for the user to answer the current question before moving to the next.

1. fullName
2. mobileNumber (CRITICAL: Extract as a continuous string of digits ONLY. e.g., "9876543210". No spaces, no commas).
3. preferredLanguage
4. state (Indian State or Union Territory)
5. businessStage (e.g., Idea, Starting out, Established)
6. businessCategory (e.g., Textiles, Pottery, Jewelry, Art)
7. annualRevenue
8. needCategory (What support do they need? e.g., Marketing, Funding, Materials)
9. existingRegistrations (e.g., MSME, GST, None)

CRITICAL INSTRUCTIONS:
1. Identify the 2-letter ISO language code the user is speaking.
2. Acknowledge their previous answer warmly but briefly.
3. Ask the NEXT missing question from the list naturally.
4. Write your conversational response ONLY in ENGLISH. (Our backend will translate it to their language automatically).
5. Extract any valid data they just provided into the "extracted_data" object.

JSON RESPONSE FORMAT:
You MUST return ONLY valid JSON in this exact format. Do not include markdown blocks or conversational text outside the JSON.
{
  "language_code": "hi",
  "extracted_data": {
    "fullName": "Priya",
    "businessCategory": "Handloom Weaving"
  },
  "english_reply": "That is wonderful work, Priya! What is your mobile number so we can stay in touch?"
}
"""

async def process_audio_chunk(audio_bytes: bytes, chat_history: list, current_language: str = "auto") -> dict | None:
    temp_filename = f"temp_user_audio_{uuid.uuid4().hex}.webm"
    with open(temp_filename, "wb") as f:
        f.write(audio_bytes)

    try:
        # STEP 1: Listen (Groq Whisper)
        whisper_kwargs = {
            "file": (temp_filename, open(temp_filename, "rb").read()),
            "model": "whisper-large-v3",
            "prompt": "Transcribe accurately in the native script."
        }
        
        if current_language and current_language != "auto":
            whisper_kwargs["language"] = current_language

        transcription = await groq_client.audio.transcriptions.create(**whisper_kwargs)
        user_text = transcription.text
        
        # FILTER CHECK: Drop empty text OR Whisper hallucinations
        if not user_text.strip() or is_hallucination(user_text):
            print(f"[Voice Worker] Ignored background static/hallucination: '{user_text}'")
            return None

        # Format history for LLM
        messages = [{"role": "system", "content": SYSTEM_PROMPT}]
        for turn in chat_history:
            if "user" in turn: messages.append({"role": "user", "content": turn["user"]})
            if "ai" in turn: messages.append({"role": "assistant", "content": turn["ai"]})
        messages.append({"role": "user", "content": user_text})

        # STEP 2: Think & Extract in English
        chat_completion = await groq_client.chat.completions.create(
            messages=messages,
            model="openai/gpt-oss-120b",
            temperature=0.1,
            response_format={"type": "json_object"}
        )
        
        ai_data = json.loads(chat_completion.choices[0].message.content)
        lang_code = ai_data.get("language_code", "en").lower()
        english_reply = ai_data.get("english_reply", "Could you repeat that?")
        extracted_data = ai_data.get("extracted_data", {})

        # STEP 3: Translate to Native Language (Deep Translator)
        if lang_code != "en":
            try:
                native_reply = GoogleTranslator(source='en', target=lang_code).translate(english_reply)
            except Exception as trans_err:
                print(f"[Translation Fallback] {trans_err}")
                native_reply = english_reply
                lang_code = "en"
        else:
            native_reply = english_reply

        # STEP 4: Speak (Edge TTS)
        voice = VOICE_MAP.get(lang_code, "en-IN-NeerjaNeural") 
        output_audio_file = f"temp_ai_reply_{uuid.uuid4().hex}.mp3"
        
        communicate = edge_tts.Communicate(native_reply, voice)
        await communicate.save(output_audio_file)

        with open(output_audio_file, "rb") as f:
            ai_audio_bytes = f.read()

        return {
            "user_text": user_text,       
            "ai_text": native_reply,          
            "ai_audio_bytes": ai_audio_bytes,
            "extracted_data": extracted_data,
            "language_code": lang_code
        }

    except Exception as e:
        print(f"[Voice Worker] Fatal pipeline error: {e}")
        return None
        
    finally:
        if os.path.exists(temp_filename): os.remove(temp_filename)
        if os.path.exists("temp_ai_reply.mp3"): os.remove("temp_ai_reply.mp3")

async def get_initial_greeting() -> dict:
    welcome_text = "Welcome to Kaarigar Connect! Which language would you prefer to speak in? You can say Hindi, Tamil, Telugu, Gujarati, or English."
    voice = "en-IN-NeerjaNeural" 
    output_file = f"temp_welcome_{uuid.uuid4().hex}.mp3"
    
    try:
        communicate = edge_tts.Communicate(welcome_text, voice)
        await communicate.save(output_file)
        with open(output_file, "rb") as f: audio_bytes = f.read()
        return {"ai_text": welcome_text, "ai_audio_bytes": audio_bytes}
    except Exception: return {}
    finally:
        if os.path.exists(output_file): os.remove(output_file)